### ISSUE TITLE
LSC not useable

### ISSUE THREAD

**Issue by R4p3z** [Lenalein2001/Lena-Utils-Modules#1]
After starting the script lsc doesn't spawn a mechanic and it doesn't play the cut scene as normally it should and  only work around i found is to restart the game

**Comment by Lenalein2001** [comment]
Works fine on my end. Apply default and send steps to reproduce.

**Comment by Lenalein2001** [comment]
> Works fine on my end. Apply default and send steps to reproduce.

You may also want to define what Module is causing this, or head to the Main Script repository.

**Comment by R4p3z** [comment]
I'm sorry i got confused my mistake i'll delete this thread
